### ISSUE TITLE
Upgrade to the last version of APIP 2.7.0-alpha.2

### ISSUE THREAD

**Issue by revollat** [mtarld/apip-ddd#2]
The processor and provider interfaces changed can you adapt the corresponding php classes please I try to do it on my own but there is no mush documentation for the 2.7/3 version for now ... 
https://github.com/api-platform/core/blob/main/CHANGELOG.md#270-alpha2
Thanks for your help.

**Comment by chalasr** [comment]
Thanks for the issue. We will adjust the code once that alpha2 is tagged

**Comment by revollat** [comment]
I figured out a way to refactor my codebase ... RTFM I guess ;)
Do you need help on this repo to maintain the codebase across versions 2.7.x ?
Because I would be glad to help if I can

**Comment by revollat** [comment]
Maybe experiment on subresources ?

**Comment by mtarld** [comment]
Of course we'd love your help! :)

**Comment by mtarld** [comment]
The code is now compatible with the 3.0 version of API Platform!
Moreover, there are no more subresources in API Platform 3, everything is resources.

Therefore I think we can close that issue but feel free to reopen it if something is missing.
Thanks!
