### ISSUE TITLE
Questions on best practice example

### ISSUE THREAD

**Issue by wazum** [mtarld/apip-ddd#23]
Thanks for the example and the presentation, but as this should be an example project for best practices(?), allow me to ask some questions:

1. **UpdateBookCommandHandler does not update**

But remove the complete book and then add it again.

```php
$this->bookRepository->remove($book);
$this->bookRepository->add($book);
```

Why would you do that?

2. **Properties on the domain model are public**

And despite telling me in the Chat on the API platform conference that they are readonly, they are not.
You even use this fact in the above-mentioned command handler:

```php
$book->name = $command->name ?? $book->name;
$book->description = $command->description ?? $book->description;
$book->author = $command->author ?? $book->author;
$book->content = $command->content ?? $book->content;
```

which contradicts ideas DDD stands for. You don't want to modify single (public) properties and expose the object to the risk of entering an invalid state!
The correct way to do this update is through a single public method that updates all (private/protected) properties at once (and checks some rules).

**Comment by chalasr** [comment]
Thanks for attending and for taking the time to open this discussion instead just bashing live.

About 1, I agree it does make sense in a real world project. A proper way to update an existing entity should be added.  

Regarding 2, these properties should definitely be immutable. If it’s not the case now, then that should be fixed.

**Comment by mtarld** [comment]
Indeed, that repository is only an API Platform integration example, it isn't intended to be a DDD/Hexagonal best practice example!

But both of your observations are great IMHO.
Therefore we must handle them, and feel free to contribute if you want to! 😉

**Comment by chalasr** [comment]
PR welcome!
