### ISSUE TITLE
Collection operations not ACID complient

### ISSUE THREAD

**Issue by sebastianstucke87** [mtarld/apip-ddd#46]
Hi! First off, thank you for this demo repo! This really did help me get my head around ApiPlattform in a non-vanilla "Symfony architecture" 😀👍

Second, I noticed in `POST api/books/anonymize`, that each SQL update statement is executed in its own transactions, instead of the entire update being done in a single transaction:

> https://github.com/mtarld/apip-ddd/blob/main/src/BookStore/Application/Command/AnonymizeBooksCommandHandler.php#L26
>
> ![](https://github.com/mtarld/apip-ddd/assets/47354551/690dbb21-f410-4d76-b544-47ff0c78aa96)

**Comment by yceruto** [comment]
Fixed in https://github.com/mtarld/apip-ddd/pull/52

**Comment by sebastianstucke87** [comment]
> Fixed in #52

Awesome, thank you! 😃🎉
