### ISSUE TITLE
Doctrine and Vendor in the Domain? 

### ISSUE THREAD

**Issue by TheProgrammer92** [mtarld/apip-ddd#48]
I just saw your conference on Youtube, which helped me a lot.
On the other hand, I don't understand why you put Doctrine in the Domain, when in the conference you said that you shouldn't do that.
Can you explain your change of position to me?

Thank you for sharing !

**Comment by chalasr** [comment]
Closing in favor #47. Note that I appreciate your effort to resubmit in english as it's generally more inclusive.
