### ISSUE TITLE
Question about hydra context

### ISSUE THREAD

**Issue by silviuvoicu** [mtarld/apip-ddd#7]
In the docs for openApicontext, in the schema section it appears Book.AnonymizeBooksCommand.jsonld and Book.DiscountBookPayload.jsonld which are the inputs for some of  custom methods for the Book resource.  But in hydra context, there's no definition or mention in the docs.jsonld
 I have added some hydraContext for the custom methods, and for discount and anonymize end point, in the expects section of the hydraContext I have DiscountBookCommand::class or AnonymizeBooksCommand::class which will result in docs.jsonld in "expects": "App\\Application\\Library\\Command\\AnonymizeBooksCommand" or "expects": "App\\Application\\Library\\Command\\DiscountBookCommand". If Book.AnonymizeBooksCommand.jsonld and Book.DiscountBookPayload.jsonld were to exists in the docs.jsonld as class definition then it should reference the expects filed.

**Comment by chalasr** [comment]
I'm sorry but I don't understand what you mean here. I'm going to close for now as the repository changed a lot meanwhile.  Feel free to comment with some screenshots or similar, so we can consider to reopen. Thanks
